---
name: deploy

on: deployment_status

jobs:
  report_status:
    runs-on: ubuntu-latest
    steps:
      - name: report
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ toJson(github.event) }}
