---
name: deploy

on: deployment_status

jobs:
  report_status:
    runs-on: ubuntu-latest
    steps:
      - name: report
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{GITHUB_CONTEXT.event}}
          echo ${{GITHUB_CONTEXT.event.deployment}}
          echo ${{GITHUB_CONTEXT.event.deployment.payload.web_url}}
