---
name: deploy

on: deployment_status

jobs:
  report_status:
    runs-on: ubuntu-latest
    steps:
      - name: report
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ github.event }}
