---
name: deploy

on: deployment_status

jobs:
  report_status:
    runs-on: ubuntu-latest
    steps:
      - name: report
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          APP_URL: ${{ github.event.deployment.payload.web_url }}
        run: |
          sh -c "curl --silent --show-error --fail $APP_URL"
